# Personal info
name: Chan Kha Vu
title: The everyday AI engineer
email: chankhavu@gmail.com

# Social links
github_username: hav4ik
stackoverflow_id: 4789373
facebook_username: hav4ik.tran
linkedin_username: ha-vu-tran-35b350a0
