# Personal info
name: Chan Kha Vu
title: The everyday AI engineer
email: chankhavu@gmail.com
ava: assets/img/myface.jpg

# Site info
logo: assets/img/ava.jpeg

# Social links
github_username: hav4ik
stackoverflow_id: 4789373
facebook_username: hav4ik.tran
linkedin_username: ha-vu-tran-35b350a0

# Comments
disqus_shortname: tranhavu
