# Personal info
name: Chan Kha Vu
title: A curious human being
email: chankhavu@gmail.com
ava: assets/img/myface.jpg
description: Hi, my name is Kha Vu (which means "summer rain"). Welcome to my personal blog!

# Site info
logo: assets/img/ava.jpeg

# Social links
github: hav4ik
stackoverflow: 4789373
twitter: chankhavu
# linkedin: ha-vu-tran-35b350a0
kaggle: chankhavu

# Comments
disqus_shortname: tranhavu

# Additional stuffs
plugins:
  - jekyll-sitemap
