# Personal info
name: Chan Kha Vu
title: A curious human being
email: chankhavu@gmail.com
ava: assets/img/myface.jpg
description: Hi, my name is Kha Vu, I'm an AI engineer, a Go player, and an amateur travel photographer. Welcome to my blog!

# Site info
logo: assets/img/ava.jpeg

# Social links
github: hav4ik
stackoverflow: 4789373
twitter: chankhavu
linkedin: ha-vu-tran-35b350a0

# Comments
disqus_shortname: tranhavu

# Additional stuffs
plugins:
  - jekyll-sitemap
